kind: pipeline

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:3.1
  environment:
    POSEIDON_SECRETS:
      from_secret: POSEIDON_SECRETS
  commands:
    - cd $(pwd)/Poseidon.API/
    - dotnet restore
    - dotnet build
    - dotnet publish -c Release -o ./bin/
- name: publish_do
  image: plugins/docker
  when:
    branch: main
  settings:
    registry:
        from_secret: DO_DOCKER_REGISTRY
    username:
        from_secret: DO_DOCKER_USERNAME
    password:
        from_secret: DO_DOCKER_PASSWORD
    repo: poseidon-container-registry/poseidon
    context: Poseidon.API
    dockerfile: Poseidon.API/Dockerfile
- name: publish_docker
  image: plugins/docker
  when:
    branch: main
  settings:
    username:
        from_secret: DOCKER_USERNAME
    password:
        from_secret: DOCKER_PASSWORD
    repo: bramhoven/poseidon
    context: Poseidon.API
    dockerfile: Poseidon.API/Dockerfile